module.exports = {
    requirements: [
        {
            label: 'Age',
            options:[
                {label: 'Child', value: 'Child'},
                {label: 'Teen', value: 'Teen'},
                {label: 'Young Adult', value: 'Young Adult'},
                {label: 'Adult', value: 'Adult'},
                {label: 'Elder', value: 'Elder'}
            ]
        },
        {
            label: 'Career',
            options:[
                {label: 'Actor', value: 'Actor'},
                {label: 'Astronaut', value: 'Astronaut'},
                {label: 'Athlete', value: 'Athlete'},
                {label: 'Babysitter', value: 'Babysitter'},
                {label: 'Barista', value: 'Barista'},
                {label: 'Business', value: 'Business'},
                {label: 'Civil Designer', value: 'Civil Designer'},
                {label: 'Conservationist', value: 'Conservationist'},
                {label: 'Critic', value: 'Critic'},
                {label: 'Criminal', value: 'Criminal'},
                {label: 'Culinary', value: 'Culinary'},
                {label: 'Detective', value: 'Detective'},
                {label: 'Driver', value: 'Driver'},
                {label: 'Doctor', value: 'Doctor'},
                {label: 'Drama Club', value: 'Drama Club'},
                {label: 'E-Sports Competitor', value: 'E-Sports Competitor'},
                {label: 'Education', value: 'Education'},
                {label: 'Engineer', value: 'Engineer'},
                {label: 'Entertainer', value: 'Entertainer'},
                {label: 'Fast Food Employee', value: 'Fast Food Employee'},
                {label: 'Fisherman', value: 'Fisherman'},
                {label: 'Freelance Artist', value: 'Freelance Artist'},
                {label: 'Freelance Crafter', value: 'Freelance Crafter'},
                {label: 'Freelance Fashion Photographer', value: 'Freelance Fashion Photographer'},
                {label: 'Freelance Programmer', value: 'Freelance Programmer'},
                {label: 'Freelance Writer', value: 'Freelance Writer'},
                {label: 'Gardner', value: 'Gardner'},
                {label: 'Interior Decorator', value: 'Interior Decorator'},
                {label: 'Law', value: 'Law'},
                {label: 'Lifeguard', value: 'Lifeguard'},
                {label: 'Manual Laborer', value: 'Manual Laborer'},
                {label: 'Military', value: 'Military'},
                {label: 'Painter', value: 'Painter'},
                {label: 'Paranormal Investigator', value: 'Paranormal Investigator'},
                {label: 'Retail Employee', value: 'Retail Employee'},
                {label: 'Politician', value: 'Politician'},
                {label: 'Salaryperson', value: 'Salaryperson'},
                {label: 'Scientist', value: 'Scientist'},
                {label: 'Scout', value: 'Scout'},
                {label: 'Secret Agent', value: 'Secret Agent'},
                {label: 'Soccar Team Player', value: 'Soccar Team Player'},
                {label: 'Social Media', value: 'Social Media'},
                {label: 'Style Influencer', value: 'Style Influencer'},
                {label: 'Tech Guru', value: 'Tech Guru'},
                {label: 'Writer', value: 'Writer'},
            ]
        },
        {
            label: 'Marital Status',
            options: [
                {label: 'Single', value: 'Single'},
                {label: 'Married', value: 'Married'}
            ]
        },
        {
            label: 'Financial Status',
            options: [
                {label: 'Poor (Less than $1000)', value: 'Poor (Less than $1000)'},
                {label: 'Middle Class ($10,000 - $30,000)', value: 'Middle Class ($10,000 - $30,000)'},
                {label: 'Wealthy (More than $30,000)', value: 'Wealthy (More than $30,000)'}
            ]
        },
        {
            label: 'Trait',
            options: [
                {label: 'Active', value: 'Active'},
                {label: 'Adventurous', value: 'Adventurous'},
                {label: 'Alien', value: 'Alien'},
                {label: 'Ambitious', value: 'Ambitious'},
                {label: 'Art Lover', value: 'Art Lover'},
                {label: 'Bookworm', value: 'Bookworm'},
                {label: 'Bro', value: 'Bro'},
                {label: 'Cat Lover', value: 'Cat Lover'},
                {label: 'Cheerful', value: 'Cheerful'},
                {label: 'Childish', value: 'Childish'},
                {label: 'Child of the Islands', value: 'Child of the Islands'},
                {label: 'Child of the Ocean', value: 'Child of the Ocean'},
                {label: 'Clumsy', value: 'Clumsy'},
                {label: 'Creative', value: 'Creative'},
                {label: 'Dance Machine', value: 'Dance Machine'},
                {label: 'Dog Lover', value: 'Dog Lover'},
                {label: 'Erratic', value: 'Erratic'},
                {label: 'Evil', value: 'Evil'},
                {label: 'Family Oriented', value: 'Family Oriented'},
                {label: 'Foodie', value: 'Foodie'},
                {label: 'Freegan', value: 'Freegan'},
                {label: 'Geek', value: 'Geek'},
                {label: 'Genius', value: 'Genius'},
                {label: 'Gloomy', value: 'Gloomy'},
                {label: 'Glutton', value: 'Glutton'},
                {label: 'Good', value: 'Good'},
                {label: 'Goofball', value: 'Goofball'},
                {label: 'Green Fiend', value: 'Green Fiend'},
                {label: 'Hates Children', value: 'Hates Children'},
                {label: 'Hot-Headed', value: 'Hot-Headed'},
                {label: 'Insider', value: 'Insider'},
                {label: 'Infected', value: 'Infected'},
                {label: 'Jealous', value: 'Jealous'},
                {label: 'Kleptomaniac', value: 'Kleptomaniac'},
                {label: 'Lazy', value: 'Lazy'},
                {label: 'Loner', value: 'Loner'},
                {label: 'Loves Outdoors', value: 'Loves Outdoors'},
                {label: 'Maker', value: 'Maker'},
                {label: 'Materialistic', value: 'Materialistic'},
                {label: 'Mean', value: 'Mean'},
                {label: 'Mermaid', value: 'Mermaid'},
                {label: 'Music Lover', value: 'Music Lover'},
                {label: 'Neat', value: 'Neat'},
                {label: 'Noncommital', value: 'Noncommital'},
                {label: 'Outgoing', value: 'Outgoing'},
                {label: 'Paranoid', value: 'Paranoid'},
                {label: 'Perfectionist', value: 'Perfectionist'},
                {label: 'Proper', value: 'Proper'},
                {label: 'Recycle Disciple', value: 'Recycle Disciple'},
                {label: 'Romantic', value: 'Romantic'},
                {label: 'Self-Absorbed', value: 'Self-Absorbed'},
                {label: 'Self-Assured', value: 'Self-Assured'},
                {label: 'Slob', value: 'Slob'},
                {label: 'Snob', value: 'Snob'},
                {label: 'Spellcaster', value: 'Spellcaster'},
                {label: 'Squeamish', value: 'Squeamish'},
                {label: 'Unflirty', value: 'Unflirty'},
                {label: 'Vampire', value: 'Vampire'},
                {label: 'Vegetarian', value: 'Vegetarian'}
            ]
        },
        {
            label: 'Skill Level 2+',
            options: [
                {label: 'Acting', value: 'Acting'},
                {label: 'Archaeology', value: 'Archaeology'},
                {label: 'Baking', value: 'Baking'},
                {label: 'Bowling', value: 'Bowling'},
                {label: 'Charisma', value: 'Charisma'},
                {label: 'Comedy', value: 'Comedy'},
                {label: 'Cooking', value: 'Cooking'},
                {label: 'Creativity', value: 'Creativity'},
                {label: 'DJ Mixing', value: 'DJ Mixing'},
                {label: 'Dancing', value: 'Dancing'},
                {label: 'Fabrication', value: 'Fabrication'},
                {label: 'Fishing', value: 'Fishing'},
                {label: 'Fitness', value: 'Fitness'},
                {label: 'Flower Arranging', value: 'Flower Arranging'},
                {label: 'Gardening', value: 'Gardening'},
                {label: 'Gourmet Cooking', value: 'Gourmet Cooking'},
                {label: 'Guitar', value: 'Guitar'},
                {label: 'Handiness', value: 'Handiness'},
                {label: 'Herbalism', value: 'Herbalism'},
                {label: 'Juice Fizzing', value: 'Juice Fizzing'},
                {label: 'Knitting', value: 'Knitting'},
                {label: 'Logic', value: 'Logic'},
                {label: 'Media Production', value: 'Media Production'},
                {label: 'Medium', value: 'Medium'},
                {label: 'Mental', value: 'Mental'},
                {label: 'Mischief', value: 'Mischief'},
                {label: 'Mixology', value: 'Mixology'},
                {label: 'Motor', value: 'Motor'},
                {label: 'Painting', value: 'Painting'},
                {label: 'Parenting', value: 'Parenting'},
                {label: 'Pet Training', value: 'Pet Training'},
                {label: 'Photography', value: 'Photography'},
                {label: 'Piano', value: 'Piano'},
                {label: 'Pipe Organ', value: 'Pipe Organ'},
                {label: 'Programming', value: 'Programming'},
                {label: 'Research and Debate', value: 'Research and Debate'},
                {label: 'Robotics', value: 'Robotics'},
                {label: 'Rock Climbing', value: 'Rock Climbing'},
                {label: 'Rocket Science', value: 'Rocket Science'},
                {label: 'Selvadoradian  Culture', value: 'Selvadoradian  Culture'},
                {label: 'Singing', value: 'Singing'},
                {label: 'Skiing', value: 'Skiing'},
                {label: 'Snowboarding', value: 'Snowboarding'},
                {label: 'Social', value: 'Social'},
                {label: 'Vampire Lore', value: 'Vampire Lore'},
                {label: 'Veterinarian', value: 'Veterinarian'},
                {label: 'Video Gaming', value: 'Video Gaming'},
                {label: 'Voilin', value: 'Voilin'},
                {label: 'Wellness', value: 'Wellness'},
                {label: 'Writing', value: 'Writing'}
            ]
        },
        {
            label: 'Celebrity Level',
            options: [
                {label: 'One-Star Celebrities', value: 'One-Star Celebrities'},
                {label: 'Two-Star Celebrities', value: 'Two-Star Celebrities'},
                {label: 'Three-Star Celebrities', value: 'Three-Star Celebrities'},
                {label: 'Four-Star Celebrities', value: 'Four-Star Celebrities'},
                {label: 'Five-Star Celebrities', value: 'Five-Star Celebrities'}
            ]
        },
    ]
}